POST http://localhost:8080/events
content-type: application/json

{
  "Name": "Test event 3",
  "Description": "Another test event (again)",
  "Location": "A test location",
  "DateTime": "2025-01-01T15:30:00.000Z"
}