DELETE http://localhost:8080/events/3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE1MjQxMTc4LCJ1c2VySWQiOjJ9.nzgUI8UYqNwXDNcvrsr5IhKnbzUSyfvFfDFzWZaI8cg